branches:
  - v[0-9]+.[0-9]+.[0-9]+
  - main
  - next
  - next-major
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

plugins:
    - '@semantic-release/commit-analyzer'
    - '@semantic-release/release-notes-generator'
    - '@semantic-release/changelog'
    - - '@semantic-release/npm'
      - npmPublish: false
    - - "@semantic-release/git"
      - assets:
        - package.json
        - package-lock.json
        - compiled/index.js
        - CHANGELOG.md
        message: |-
          chore(release): ${nextRelease.version} [skip ci]

          ${nextRelease.notes}
    - '@semantic-release/github'
